### ISSUE TITLE
'stop' feature in chainable methods

### ISSUE THREAD

**Issue by G33kLabs** [fshost/api-chain#1]
Hello,

I've just implemented your package and it works really well ! Thank you for that !

In my use case, it will be a good feature to add a `stop()` method like used in jQuery to stop and reset the fx queue. Very helpful in an async ecosystem based on events.

What do you think about this feature ?

**Comment by fshost** [comment]
jQuery definitely is more robust in terms of async control than this library, but if you have a conditional you can simply create your own stop function and use that to evaluate whether to advance the queue or not.  If you want to explicitly clear the queue for some reason you can set the _callbacks and _deferreds properties to empty arrays in your own stop function.  The core code is small and internally documented to help with issues like this.  In the interests of keeping this lightweight I'd rather hold off on hard-coding a stop function in the core unless/until it becomes a necessity (e.g. show me a use case scenario) and/or there is a lot of demand.
