### ISSUE TITLE
calling method from another method

### ISSUE THREAD

**Issue by jandrieu** [fshost/api-chain#2]
How do you call a method from another method so that it acts as a subchain?

I thought I had this working, but then I restructured my code and can't get it working again.

Here's a simplified case, where I would expect the printouts to be A, B, C, D, but they are A, B, D, C.

The tricky part is that the second method in the chain depends on an asynchronous callback. And that's where it comes apart.

``` javascript
#!/usr/bin/env node

var api = require('api-chain');

var tester = api.create({
  A: A,
  B: B,
  C: C,
  D: D,
});

function A(next) {
  console.log('A');
  this
    .B()
    .C()
  next();
}

function B(next) {
  setTimeout(function(){
    console.log('B');
    next();
  },5000);
}

function C(next) {
  console.log('C');
  next();
}

function D(next) {
  console.log('D');
  next();
}

tester
  .A()
  .D()
```

**Comment by jandrieu** [comment]
I also tried it with A written as 

``` javascript
function A(next) {
  console.log('A');
  this
    .B()
    .C()
    .next();
}
```

**Comment by jandrieu** [comment]
For what it's worth, I was able to get essentially the desired functionality using chainit3. https://github.com/kapouer/chainit3

**Comment by fshost** [comment]
The code has been modified to work more intuitively with nested method calls.

**Comment by fshost** [comment]
There is a typo in the example above but the correct version of it has been added to the examples subdir as nested.js and a test case has also been created for calling nested methods.
